spring:
  application:
    name: conversion-factor  datasource:    url: jdbc:h2:mem:conversiondb
    driver-class-name: org.h2.Driver
    username: ibm
    password: ibm  h2:    console:      enabled: true  jpa:    show-sql: true
    
eureka:  instance:    instance-id: ${spring.application.name}:${random.int}  client:    service-url:      defaultZone: http://localhost:8300/eureka
    
    
server:  port: 8100
  
  
  
  