---
apiVersion: v1
kind: Service
metadata:
  labels: 
    app: convertcurrency
    version: v1
  name: convertcurrency
spec:
  ports:
    -
      name: http
      port: 8200
      targetPort: 8200
      
  selector: 
    app: convertcurrency
    version: v1
  type: NodePort