spring:
  application:
    name: convert-currency
    
server:
  port: 8200
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    service-url:
      defaultZone: http://localhost:8300/eureka