spring:
  application:
    name: convert-currency  zipkin:    base-url: http://192.168.99.100:9411  sleuth:    sampler:      probability: 1.0    trace-id128: true
    
server:
  port: 8200
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    service-url:
      defaultZone: http://localhost:8300/eureka
      
      